#!/bin/bash

set -e

mkdir -p /var/lib/scylla/conf
cp -fa /etc/scylla/* /var/lib/scylla/conf

IP=$(hostname -i)
RACKDC_FILE="/var/lib/scylla/conf/cassandra-rackdc.properties"

[ "$DC" != "" ] && echo dc=$DC >> $RACKDC_FILE
[ "$RACK" != "" ] && echo rack="$RACK" >> $RACKDC_FILE
echo prefer_local=true >> $RACKDC_FILE

OPTS=""
[ "$CLUSTER_NAME" != "" ] && \
    OPTS="$OPTS --cluster-name $CLUSTER_NAME"
[ "$SEEDS" != "" ] && \
    OPTS="$OPTS --seed-provider-parameters seeds=$SEEDS" || \
    OPTS="$OPTS --seed-provider-parameters seeds=$IP"
[ "$SNITCH" != "" ] && \
    OPTS="$OPTS --endpoint-snitch $SNITCH"
[ "$LISTEN_ADDRESS" != "" ] && \
    OPTS="$OPTS --listen-address $LISTEN_ADDRESS" || \
    OPTS="$OPTS --listen-address $IP"
[ "$BROADCAST_ADDRESS" != "" ] && \
    OPTS="$OPTS --broadcast-address $BROADCAST_ADDRESS" && \
    OPTS="$OPTS --broadcast-rpc-address $BROADCAST_ADDRESS"
[ "$RPC_ADDRESS" != "" ] && \
    OPTS="$OPTS --rpc-address $RPC_ADDRESS" || \
    OPTS="$OPTS --rpc-address $IP"
[ "$START_RPC" != "" ] && \
    OPTS="$OPTS --start-rpc $START_RPC"
[ "$API_ADDRESS" != "" ] && \
    OPTS="$OPTS --api-address $API_ADDRESS"
[ "$TOKENS" != "" ] && \
    OPTS="$OPTS --num-tokens $TOKENS"

/usr/bin/scylla \
    --log-to-syslog 1 \
    --log-to-stdout 0 \
    --developer-mode true \
    --default-log-level info \
    --options-file /var/lib/scylla/conf/scylla.yaml \
    --network-stack posix \
    $OPTS
