FROM gliderlabs/logspout:master

RUN # ENV KAFKA_COMPRESSION_CODEC snappy
RUN  #  KAFKA_TEMPLATE="{\"time\"=\"{{js .Time}}\", \"container_name\"=\"{{js .Container.Name}}\", \"node\"=\"{{js .Container.Node}}\", \"image\"=\"{{js .Container.Image}}\", \"source\"=\"{{js .Source}}\", \"data\"=\"{{js .Data}}\"}"
