yumfilebeat.prospectors:
- paths:
    - /opt/couchbase/var/lib/couchbase/logs/babysitter.log
    - /opt/couchbase/var/lib/couchbase/logs/couchdb.log
    - /opt/couchbase/var/lib/couchbase/logs/debug.log
    - /opt/couchbase/var/lib/couchbase/logs/error.log
    - /opt/couchbase/var/lib/couchbase/logs/info.log
    - /opt/couchbase/var/lib/couchbase/logs/mapreduce_errors.log
    - /opt/couchbase/var/lib/couchbase/logs/metakv.log
    - /opt/couchbase/var/lib/couchbase/logs/ns_couchdb.log
    - /opt/couchbase/var/lib/couchbase/logs/reports.log
    - /opt/couchbase/var/lib/couchbase/logs/stats.log
    - /opt/couchbase/var/lib/couchbase/logs/xdcr.log
    - /opt/couchbase/var/lib/couchbase/logs/views.log
    - /opt/couchbase/var/lib/couchbase/logs/xdcr_errors.log
    - /opt/couchbase/var/lib/couchbase/logs/xdcr_trace.log
  encoding: utf-8
  document_type: couchbase
  multiline:
    pattern: '^\[[a-z]+:[a-z]+,'
    negate: true
    match: after

- paths:
    - /opt/couchbase/var/lib/couchbase/logs/indexer.log
    - /opt/couchbase/var/lib/couchbase/logs/projector.log
  encoding: utf-8
  document_type: couchbase
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}T'
    negate: true
    match: after

- paths:
    - /opt/couchbase/var/lib/couchbase/logs/goxdcr.log
  encoding: utf-8
  document_type: couchbase
  multiline:
    pattern: '^[a-z]+ [0-9]{4}-[0-9]{2}-[0-9]{2}T'
    negate: true
    match: after

- paths:
    - /opt/couchbase/var/lib/couchbase/logs/http_access.log
    - /opt/couchbase/var/lib/couchbase/logs/http_access_internal.log
    - /opt/couchbase/var/lib/couchbase/logs/query.log
    - /tmp/supervisord.log
  encoding: utf-8
  document_type: couchbase

output.console:
  enabled: ${CONSOLE_LOGS:true}

output.kafka:
  enabled: ${KAFKA_LOGS:false}
  version: "0.10"
  hosts: ${KAFKA_BROKER_LIST}
  topic: ${KAFKA_TOPIC:"couchbase_logs"}
  partition.round_robin:
    reachable_only: true
